[package]
name = "minparse"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A minimalist argument parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
